// Generated by tooling/build-app-visual-kit.py. Component-color mapping only.
import 'package:flutter/material.dart';

abstract final class PlectaraAppLightColors {
  static const card = Color(0xFFE9F3EF);
  static const text = Color(0xFF192D38);
  static const textSecondary = Color(0xFF506F7E);
  static const control = Color(0xFFFFFFFF);
  static const soft = Color(0xFFE9F3EF);
  static const primary = Color(0xFF287E80);
  static const onPrimary = Color(0xFFFFFFFF);
  static const link = Color(0xFF206668);
  static const controlOutline = Color(0xFF567788);
  static const decorativeOutline = Color(0xFFC88764);
  static const navigation = Color(0xFFE9F3EF);
  static const navigationSelected = Color(0xFFFFFFFF);
  static const attention = Color(0xFF845800);
}

abstract final class PlectaraAppDarkColors {
  static const card = Color(0xFF192D38);
  static const text = Color(0xFFFAF8F4);
  static const textSecondary = Color(0xFFB8CBCB);
  static const control = Color(0xFF264C4B);
  static const soft = Color(0xFF223D49);
  static const primary = Color(0xFF76B7A5);
  static const onPrimary = Color(0xFF192D38);
  static const link = Color(0xFF8DC7B7);
  static const controlOutline = Color(0xFF8DA4A6);
  static const decorativeOutline = Color(0xFFC88764);
  static const navigation = Color(0xFF192D38);
  static const navigationSelected = Color(0xFF264C4B);
  static const attention = Color(0xFFE5B86A);
}
