"""Validate and package the approved app visual assets without regenerating artwork."""
import base64
import hashlib
import html
import importlib.util
import json
from pathlib import Path
import re
import shutil
from urllib.parse import unquote
import zipfile

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
KIT = ROOT / "assets/app/plectara"
PUBLIC = ROOT / "docs/assets/app/plectara"
SPEC = ROOT / "docs/specs/02-design/app-visuals.md"
ZIP_NAME = "plectara-app-visuals-v1.zip"


def write_json(path, value):
    path.write_text(json.dumps(value, indent=2) + "\n")


def bundled_specification():
    def link(match):
        target = match.group(1)
        if target.startswith(("https:", "http:", "#", "mailto:")):
            return match.group(0)
        file, separator, anchor = target.partition("#")
        resolved = (SPEC.parent / unquote(file)).resolve()
        if resolved.is_relative_to(PUBLIC):
            replacement = resolved.relative_to(PUBLIC).as_posix()
        elif resolved.is_relative_to(ROOT / "docs"):
            relative = resolved.relative_to(ROOT / "docs")
            if relative.suffix == ".md":
                relative = relative.parent if relative.name == "README.md" else relative.with_suffix("")
                replacement = "https://pl-os.plectara.com/" + relative.as_posix().rstrip("/") + "/"
            else:
                replacement = "https://pl-os.plectara.com/" + relative.as_posix()
        else:
            raise ValueError(f"Unmapped package link: {target}")
        return "](" + replacement + (separator + anchor if separator else "") + ")"
    return re.sub(r"\]\(([^\s)]+)\)", link, SPEC.read_text())


def adapters(tokens):
    def css_name(name):
        return re.sub(r"([A-Z])", lambda match: "-" + match.group(1).lower(), name)
    def css_block(selector, palette):
        lines = [f"  --plectara-app-{css_name(name)}: {value};" for name, value in palette.items()]
        return selector + " {\n" + "\n".join(lines) + "\n}\n"
    css = "/* Generated by tooling/build-app-visual-kit.py; woven app component aliases. */\n"
    css += css_block(".plectara-woven-app", tokens["themes"]["light"])
    css += css_block('.plectara-woven-app[data-theme="dark"]', tokens["themes"]["dark"])
    css += "@media (prefers-color-scheme: dark) {\n" + css_block(".plectara-woven-app:not([data-theme])", tokens["themes"]["dark"]) + "}\n"
    (KIT / "adapters/plectara-app-colors.css").write_text(css)
    dart = "// Generated by tooling/build-app-visual-kit.py. Component-color mapping only.\nimport 'package:flutter/material.dart';\n\n"
    for mode, palette in tokens["themes"].items():
        dart += f"abstract final class PlectaraApp{mode.capitalize()}Colors {{\n"
        dart += "\n".join(f"  static const {name} = Color(0xFF{value[1:]});" for name, value in palette.items())
        dart += "\n}\n\n"
    (KIT / "adapters/plectara_app_colors.dart").write_text(dart.rstrip() + "\n")


def contrast_report(tokens):
    module = importlib.util.spec_from_file_location("component_contrast", ROOT / "tooling/check-component-contrast.py")
    checker = importlib.util.module_from_spec(module)
    module.loader.exec_module(checker)
    pairs = []
    for mode, palette in tokens["themes"].items():
        for surface in ["card", "control", "soft", "navigation", "navigationSelected"]:
            for role in ["text", "textSecondary", "link", "attention"]:
                pairs.append(dict(name=f"{mode}: {role} / {surface}", theme=mode, roles=f"{role} / {surface}", foreground=palette[role], background=palette[surface], minimum=4.5))
            pairs.append(dict(name=f"{mode}: required control outline / {surface}", theme=mode, roles=f"controlOutline / {surface}", foreground=palette["controlOutline"], background=palette[surface], minimum=3))
        pairs += [
            dict(name=f"{mode}: filled action label", theme=mode, roles="onPrimary / primary", foreground=palette["onPrimary"], background=palette["primary"], minimum=4.5),
            dict(name=f"{mode}: screenshot chart marks", theme=mode, roles="link / card", foreground=palette["link"], background=palette["card"], minimum=3),
            dict(name=f"{mode}: selected navigation cue", theme=mode, roles="link / navigationSelected", foreground=palette["link"], background=palette["navigationSelected"], minimum=3),
        ]
    pairs.append(dict(name="Protected header text over conservative white photo base", theme="both", roles="header foreground / ink shade at 56% position", foreground=tokens["header"]["foreground"], background="#FFFFFF", backgroundLayers=[dict(color=tokens["header"]["ink"], alpha=0.66)], minimum=4.5))
    pairs.append(dict(name="Header settings and status icons on opaque ink", theme="both", roles="header foreground / header ink", foreground=tokens["header"]["foreground"], background=tokens["header"]["ink"], minimum=3))
    results = []
    for pair in pairs:
        actual, passed = checker.evaluate(pair)
        assert passed, f"Contrast failure: {pair['name']} {actual:.6f}:1"
        results.append({**pair, "contrast": actual, "passed": passed})
    write_json(KIT / "verification/contrast-fixtures.json", {"scope": "Approved app-local opaque combinations and protected header compositing; not native or legal compliance.", "pairs": pairs})
    decorative = []
    for mode, palette in tokens["themes"].items():
        for surface in ["card", "control"]:
            ratio = checker.contrast(checker.rgb(palette["decorativeOutline"]), checker.rgb(palette[surface]))
            decorative.append(dict(name=f"{mode}: copper / {surface}", contrast=ratio, role="decorative only; excluded from required-boundary assertions"))
    write_json(KIT / "verification/contrast-report.json", {"checks": len(results), "failures": 0, "minimum_text_ratio": min(row["contrast"] for row in results if row["minimum"] == 4.5), "scope": "Measured app-local pairs; actual image crops, native state layers, geometry and assistive-technology behavior require consuming-app verification.", "results": results, "decorative_only": decorative})
    return len(results)


def main():
    fragment_bytes = (KIT / "reference/approved-mockup-fragment.html").read_bytes()
    fragment = fragment_bytes.decode()
    approval = json.loads((KIT / "source/approval.json").read_text())
    assert hashlib.sha256(fragment_bytes).hexdigest() == approval["fragment_sha256"], "Approved review-source drift"
    texture_url = re.search(r"--p-yarn:url\('([^']+)'", fragment)[1]
    logo_url = re.search(r"const logo='([^']+)'", fragment)[1]
    font_url = re.search(r"src:url\('([^']+)'", fragment)[1]
    for relative, url in [("textures/plectara-widget-yarn-gentle-focus-v1.webp", texture_url), ("logos/plectara-horizontal-reversed.svg", logo_url), ("fonts/Inter-review-subset.woff", font_url)]:
        assert base64.b64decode(url.split(",", 1)[1]) == (KIT / relative).read_bytes(), relative
    for name in ["plectara-widget-yarn-gentle-focus-v1.webp", "plectara-widget-yarn-gentle-focus-v1.png"]:
        assert (KIT / "textures" / name).read_bytes() == (ROOT / "assets/widgets/plectara/textures" / name).read_bytes(), name
    assert (KIT / "logos/plectara-horizontal-reversed.svg").read_bytes() == (ROOT / "assets/brand/plectara/source/plectara-horizontal-reversed.svg").read_bytes(), "Canonical logo drift"
    standalone = html.unescape((KIT / "reference/approved-app.html").read_text())
    assert fragment in standalone, "Offline reference does not include exact approved fragment"
    assert (KIT / "reference/lucide.min.js").read_text() in standalone, "Offline icon library drift"
    tokens = json.loads((KIT / "app-visual-tokens.json").read_text())
    mapping = dict(card="card", text="text", textSecondary="muted", control="control", soft="soft", primary="action", onPrimary="on-action", link="link", controlOutline="outline", decorativeOutline="border", navigation="nav", navigationSelected="selected", attention="warning")
    defaults = dict(re.findall(r"--p-([a-z-]+):(#[0-9A-Fa-f]{6})", re.search(r'\.p-phone\{([^}]+)\}', fragment)[1]))
    for mode, pattern in [("light", r'\.p-phone\{([^}]+)\}'), ("dark", r'\.p-phone\[data-theme="dark"\]\{([^}]+)\}')]:
        # The dark selector inherits the copper edge from the base declaration.
        declared = defaults | dict(re.findall(r"--p-([a-z-]+):(#[0-9A-Fa-f]{6})", re.search(pattern, fragment)[1]))
        for role, css_role in mapping.items():
            actual = declared[css_role]
            assert actual.upper() == tokens["themes"][mode][role], (mode, role)
    for screen in ["today", "timeline", "charts", "insights", "today-empty"]:
        for mode in ["light", "dark"]:
            with Image.open(KIT / f"previews/{screen}-{mode}.png") as image:
                assert image.width == 714 and image.height > 1000, (screen, mode)
                assert image.mode in ["RGB", "RGBA"], (screen, mode)
    for report_name in ["browser-review.json", "offline-review.json"]:
        browser = json.loads((KIT / "verification" / report_name).read_text())
        assert not browser["errors"], report_name
        assert len(browser["reviews"]) == 8, report_name
        assert all(not row["pageOverflow"] and not row["issues"] and row["unrenderedIcons"] == 0 and row["fontLoaded"] for row in browser["reviews"]), report_name
        assert all(browser["interactions"].values()), report_name
    adapters(tokens)
    checks = contrast_report(tokens)
    (KIT / "specification.md").write_text(bundled_specification())
    inventory = []
    for path in sorted(KIT.rglob("*")):
        if not path.is_file() or path.name in ["manifest.json", ZIP_NAME, ".DS_Store"]:
            continue
        relative = path.relative_to(KIT).as_posix()
        entry = dict(file=relative, role=relative.split("/", 1)[0], bytes=path.stat().st_size, sha256=hashlib.sha256(path.read_bytes()).hexdigest())
        if path.suffix.lower() in [".png", ".webp"]:
            with Image.open(path) as image:
                entry.update(width=image.width, height=image.height, mode=image.mode)
        inventory.append(entry)
    write_json(KIT / "manifest.json", dict(asset_id="plectara-app-visuals", version=1, status="owner-approved design reference; PL-OS v2.6.0 publication pending", approval_date="2026-09-28", specification="docs/specs/02-design/app-visuals.md", default_texture=tokens["texture"]["file"], screenshot_scale=2, populated_screenshots=8, empty_today_screenshots=2, comparison_sheets=4, native_implementation_included=False, files=inventory))
    with zipfile.ZipFile(KIT / ZIP_NAME, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for entry in inventory + [dict(file="manifest.json")]:
            info = zipfile.ZipInfo(entry["file"], (2026, 9, 28, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, (KIT / entry["file"]).read_bytes())
    PUBLIC.mkdir(parents=True, exist_ok=True)
    shutil.copytree(KIT, PUBLIC, dirs_exist_ok=True)
    with zipfile.ZipFile(KIT / ZIP_NAME) as archive:
        for entry in inventory + [dict(file="manifest.json")]:
            source = (KIT / entry["file"]).read_bytes()
            assert archive.read(entry["file"]) == source, entry["file"]
            assert (PUBLIC / entry["file"]).read_bytes() == source, entry["file"]
    print(json.dumps(dict(files=len(inventory), contrast_checks=checks, zip_bytes=(KIT / ZIP_NAME).stat().st_size, approved_source=True, exact_artwork=True, ten_screen_previews=True, zip_and_docs_parity=True)))


if __name__ == "__main__":
    main()
