"""Check component color contracts, including optional composited audit fixtures.

Default: validate current semantic roles and compare the committed report.
--write: regenerate that report. --fixtures FILE: check literal app color pairs.
Fixtures are measurements, not an automatic scan or a full accessibility audit.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / 'docs/specs/02-design/plectara-component-contrast-report.md'


def rgb(color):
    if len(color) != 7 or color[0] != '#':
        raise ValueError(f'Expected opaque #RRGGBB color: {color!r}')
    return tuple(int(color[i:i + 2], 16) / 255 for i in (1, 3, 5))


def composite(foreground, background, alpha):
    if not 0 <= alpha <= 1:
        raise ValueError('Alpha must be between 0 and 1')
    return tuple(f * alpha + b * (1 - alpha)
                 for f, b in zip(foreground, background))


def luminance(color):
    linear = (v / 12.92 if v <= .04045 else ((v + .055) / 1.055) ** 2.4
              for v in color)
    return sum(v * w for v, w in zip(linear, (.2126, .7152, .0722)))


def contrast(foreground, background):
    low, high = sorted((luminance(foreground), luminance(background)))
    return (high + .05) / (low + .05)


def evaluate(pair):
    background = rgb(pair['background'])
    # Ordered bottom to top, in encoded sRGB. No rounding before comparison.
    for layer in pair.get('backgroundLayers', []):
        background = composite(rgb(layer['color']), background, layer['alpha'])
    foreground = composite(rgb(pair['foreground']), background,
                           pair.get('foregroundAlpha', 1))
    actual = contrast(foreground, background)
    return actual, actual >= pair['minimum']


def component_pairs(tokens):
    # Each entry names a real use of a role; repeated colors can diverge later.
    uses = [
        ('Body and value text', 'text', 4.5),
        ('Supporting text and chart labels', 'textSecondary', 4.5),
        ('Input placeholder', 'textSecondary', 4.5),
        ('Links and secondary button labels', 'link', 4.5),
        ('Success label', 'success', 4.5),
        ('Warning label', 'warning', 4.5),
        ('Error label', 'critical', 4.5),
        ('Information label', 'info', 4.5),
        ('AI label', 'ai', 4.5),
        ('Required control outline', 'border', 3),
        ('Focus or selected outline', 'focus', 3),
        ('Validation outline', 'critical', 3),
        ('Selected radio indicator', 'primary', 3),
        ('Chart series 1', 'primary', 3),
        ('Chart series 2', 'textSecondary', 3),
        ('AI chart overlay', 'ai', 3),
    ]
    for mode in ('light', 'dark'):
        palette = tokens[mode]
        for surface in ('background', 'surface', 'surfaceMuted', 'selected'):
            for name, role, minimum in uses:
                yield dict(theme=mode, name=f'{name} / {surface}',
                           roles=f'{role} / {surface}',
                           foreground=palette[role], background=palette[surface],
                           minimum=minimum)
        for name, role in [('Primary button', 'primary'),
                           ('Hovered or pressed primary button', 'primaryHover'),
                           ('Secondary filled action', 'link'),
                           ('Information filled action', 'info'),
                           ('AI filled button', 'ai'),
                           ('Destructive filled button', 'critical')]:
            yield dict(theme=mode, name=name, roles=f'onPrimary / {role}',
                       foreground=palette['onPrimary'], background=palette[role],
                       minimum=4.5)


def render(pairs):
    rows = []
    failed = []
    for pair in pairs:
        actual, passed = evaluate(pair)
        if not passed:
            failed.append((pair['name'], actual, pair['minimum']))
        rows.append(f"| {pair['theme']} | {pair['name']} | {pair['roles']} | "
                    f"{actual:.4f}:1 | {pair['minimum']}:1 | "
                    f"{'Pass' if passed else 'FAIL'} |")
    report = (
        '# Component contrast checks\n\n'
        'Generated by `tooling/check-component-contrast.py --write` from the '
        'current semantic palette. These checks cover the opaque combinations '
        'specified in [Dark Mode & Accessibility](dark-mode.md), including '
        'selected surfaces, hints, validation, chart strokes, and filled actions.\n\n'
        f'{len(rows)} checks; {len(failed)} failures. Ratios are displayed to four '
        'decimals; pass/fail uses the unrounded value.\n\n'
        'The existing [brand palette report](plectara-contrast-report.md) remains '
        'a separate baseline. Neither report tests screen-reader behavior, '
        'component geometry, chart-series adjacency, actual app overrides, '
        'framework state layers, or legal compliance. Changed surfaces or '
        'transparency require their own measured fixtures. Decorative dividers '
        'and genuinely disabled controls are outside these contrast assertions.\n\n'
        '| Theme | Component use | Roles | Contrast | Minimum | Result |\n'
        '| --- | --- | --- | --- | --- | --- |\n'
        + '\n'.join(rows) + '\n'
    )
    return report, failed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--fixtures', type=Path)
    args = parser.parse_args()
    if args.fixtures:
        if args.write:
            parser.error('--write cannot be combined with --fixtures')
        fixtures = json.loads(args.fixtures.read_text())
        failures = 0
        for pair in fixtures['pairs']:
            actual, passed = evaluate(pair)
            failures += not passed
            print(f"{'PASS' if passed else 'FAIL'} {pair['name']}: "
                  f"{actual:.4f}:1 (minimum {pair['minimum']}:1)")
        print(f'{len(fixtures["pairs"])} fixture checks; {failures} failures.')
        return int(failures > 0)
    tokens = json.loads((ROOT / 'assets/tokens/color.tokens.json').read_text())
    pairs = list(component_pairs(tokens))
    report, failed = render(pairs)
    if failed:
        for name, actual, minimum in failed:
            print(f'FAIL {name}: {actual:.6f}:1 < {minimum}:1')
        return 1
    if args.write:
        REPORT.write_text(report)
    elif not REPORT.exists() or REPORT.read_text() != report:
        print('Component contrast report is stale; run with --write.')
        return 1
    print(f'{len(pairs)} component contrast checks passed; report verified.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
